<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251107000316 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE paiement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, montant NUMERIC(10, 2) NOT NULL, date_paiement DATE NOT NULL, mode_paiement VARCHAR(50) NOT NULL, consultation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B1DC7A1E62FF6CDF ON paiement (consultation_id)');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1E62FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE consultation ADD date_consultation DATE NOT NULL');
        $this->addSql('ALTER TABLE consultation ADD diagnostic TEXT NOT NULL');
        $this->addSql('ALTER TABLE consultation ADD notes TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE consultation ADD patient_id INT NOT NULL');
        $this->addSql('ALTER TABLE consultation ADD medecin_id INT NOT NULL');
        $this->addSql('ALTER TABLE consultation ADD rendez_vous_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A66B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A64F31A84 FOREIGN KEY (medecin_id) REFERENCES medecin (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A691EF7EAA FOREIGN KEY (rendez_vous_id) REFERENCES rendez_vous (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_964685A66B899279 ON consultation (patient_id)');
        $this->addSql('CREATE INDEX IDX_964685A64F31A84 ON consultation (medecin_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_964685A691EF7EAA ON consultation (rendez_vous_id)');
        $this->addSql('ALTER TABLE ligne_ordonnance ADD quantite INT NOT NULL');
        $this->addSql('ALTER TABLE ligne_ordonnance ADD posologie VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE ligne_ordonnance ADD ordonnance_id INT NOT NULL');
        $this->addSql('ALTER TABLE ligne_ordonnance ADD medicament_id INT NOT NULL');
        $this->addSql('ALTER TABLE ligne_ordonnance ADD CONSTRAINT FK_71E7DC712BF23B8F FOREIGN KEY (ordonnance_id) REFERENCES ordonnance (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_ordonnance ADD CONSTRAINT FK_71E7DC71AB0D61F7 FOREIGN KEY (medicament_id) REFERENCES medicament (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_71E7DC712BF23B8F ON ligne_ordonnance (ordonnance_id)');
        $this->addSql('CREATE INDEX IDX_71E7DC71AB0D61F7 ON ligne_ordonnance (medicament_id)');
        $this->addSql('ALTER TABLE medecin ALTER nom TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE medecin ALTER prenom TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE medecin ALTER specialite TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE medecin ALTER telephone TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE medicament ADD nom VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE medicament ADD description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE ordonnance ADD date_emission DATE NOT NULL');
        $this->addSql('ALTER TABLE ordonnance ADD commentaires TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE ordonnance ADD consultation_id INT NOT NULL');
        $this->addSql('ALTER TABLE ordonnance ADD CONSTRAINT FK_924B326C62FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_924B326C62FF6CDF ON ordonnance (consultation_id)');
        $this->addSql('ALTER TABLE patient ALTER nom TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE patient ALTER prenom TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE patient ALTER telephone TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE rendez_vous ADD date_rdv DATE NOT NULL');
        $this->addSql('ALTER TABLE rendez_vous ADD heure TIME(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE rendez_vous ADD statut VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE rendez_vous DROP date');
        $this->addSql('ALTER TABLE rendez_vous DROP motif');
        $this->addSql('ALTER TABLE secretaire ALTER nom TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE secretaire ALTER prenom TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE secretaire ALTER telephone TYPE VARCHAR(20)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA app');
        $this->addSql('CREATE SCHEMA pgbouncer');
        $this->addSql('CREATE SCHEMA realtime');
        $this->addSql('CREATE SCHEMA extensions');
        $this->addSql('CREATE SCHEMA vault');
        $this->addSql('CREATE SCHEMA graphql_public');
        $this->addSql('CREATE SCHEMA graphql');
        $this->addSql('CREATE SCHEMA auth');
        $this->addSql('CREATE SCHEMA storage');
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE paiement DROP CONSTRAINT FK_B1DC7A1E62FF6CDF');
        $this->addSql('DROP TABLE paiement');
        $this->addSql('ALTER TABLE consultation DROP CONSTRAINT FK_964685A66B899279');
        $this->addSql('ALTER TABLE consultation DROP CONSTRAINT FK_964685A64F31A84');
        $this->addSql('ALTER TABLE consultation DROP CONSTRAINT FK_964685A691EF7EAA');
        $this->addSql('DROP INDEX IDX_964685A66B899279');
        $this->addSql('DROP INDEX IDX_964685A64F31A84');
        $this->addSql('DROP INDEX UNIQ_964685A691EF7EAA');
        $this->addSql('ALTER TABLE consultation DROP date_consultation');
        $this->addSql('ALTER TABLE consultation DROP diagnostic');
        $this->addSql('ALTER TABLE consultation DROP notes');
        $this->addSql('ALTER TABLE consultation DROP patient_id');
        $this->addSql('ALTER TABLE consultation DROP medecin_id');
        $this->addSql('ALTER TABLE consultation DROP rendez_vous_id');
        $this->addSql('ALTER TABLE ligne_ordonnance DROP CONSTRAINT FK_71E7DC712BF23B8F');
        $this->addSql('ALTER TABLE ligne_ordonnance DROP CONSTRAINT FK_71E7DC71AB0D61F7');
        $this->addSql('DROP INDEX IDX_71E7DC712BF23B8F');
        $this->addSql('DROP INDEX IDX_71E7DC71AB0D61F7');
        $this->addSql('ALTER TABLE ligne_ordonnance DROP quantite');
        $this->addSql('ALTER TABLE ligne_ordonnance DROP posologie');
        $this->addSql('ALTER TABLE ligne_ordonnance DROP ordonnance_id');
        $this->addSql('ALTER TABLE ligne_ordonnance DROP medicament_id');
        $this->addSql('ALTER TABLE medecin ALTER nom TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE medecin ALTER prenom TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE medecin ALTER specialite TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE medecin ALTER telephone TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE medicament DROP nom');
        $this->addSql('ALTER TABLE medicament DROP description');
        $this->addSql('ALTER TABLE ordonnance DROP CONSTRAINT FK_924B326C62FF6CDF');
        $this->addSql('DROP INDEX IDX_924B326C62FF6CDF');
        $this->addSql('ALTER TABLE ordonnance DROP date_emission');
        $this->addSql('ALTER TABLE ordonnance DROP commentaires');
        $this->addSql('ALTER TABLE ordonnance DROP consultation_id');
        $this->addSql('ALTER TABLE patient ALTER nom TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE patient ALTER prenom TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE patient ALTER telephone TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE rendez_vous ADD date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE rendez_vous ADD motif VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE rendez_vous DROP date_rdv');
        $this->addSql('ALTER TABLE rendez_vous DROP heure');
        $this->addSql('ALTER TABLE rendez_vous DROP statut');
        $this->addSql('ALTER TABLE secretaire ALTER nom TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE secretaire ALTER prenom TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE secretaire ALTER telephone TYPE VARCHAR(255)');
    }
}
